apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: learn2code-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Dengoan969/learn2code-backend.git
    targetRevision: devops
    path: src/chart
    helm:
      valueFiles:
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: learn2code
  syncPolicy:
    syncOptions:
      - CreateNamespace=true