apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "learn2code-api.fullname" . }}-data
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "learn2code-api.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  storageClassName: {{ .Values.persistence.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}