apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "learn2code-api.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "learn2code-api.labels" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountToken }}